development:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: alex_journal_development

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis-15105.c1.ap-southeast-1-1.ec2.cloud.redislabs.com:15105" } %>
  channel_prefix: alex_journal_production
